name: rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:          
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - name: macos-latest
      if: matrix.platform == 'macos-latest'
      uses: actions/checkout@v3
      with:
        run: cargo build --release --target=aarch64-apple-darwin

    - name: Upload exe file
      uses: actions/upload-artifact@v3
      with:
        name: qwen-rs
        path: |
          target\release\*.exe
          target/release/qwen-rs
          target/aarch64-apple-darwin/release/qwen-rs